# Generated by Django 3.2.8 on 2021-12-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
