# Generated by Django 3.2.8 on 2021-12-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211220_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type_of_plan',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
