# Generated by Django 3.2.8 on 2021-11-28 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date_of_acceptance',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_of_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
