# Generated by Django 3.2.8 on 2021-11-28 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211128_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='date_of_upgradation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
