# Generated by Django 3.2.8 on 2021-11-28 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_upgrade_date_of_upgradation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_of_acceptance',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_of_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
