# Generated by Django 3.2.8 on 2021-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_upgrade_date_of_upgradation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_of_acceptance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='date_of_upgradation',
            field=models.DateField(null=True),
        ),
    ]
