# Generated by Django 3.2.8 on 2021-12-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contract_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='upgraded_to',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
