# Generated by Django 3.2.8 on 2021-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_customerquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquery',
            name='asked_on',
            field=models.DateTimeField(null=True),
        ),
    ]
