# Generated by Django 3.2.8 on 2021-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customerquery_asked_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquery',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
