# Generated by Django 3.2.8 on 2021-12-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaymentdetail',
            name='date_of_payment',
            field=models.DateTimeField(null=True),
        ),
    ]
