# Generated by Django 3.2.8 on 2021-12-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_customerpaymentdetail_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpaymentdetail',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
