# Generated by Django 3.2.8 on 2021-12-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_customerpaymentdetail_fees_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpaymentdetail',
            name='fees_taken',
            field=models.IntegerField(null=True),
        ),
    ]
